export const REPOS_FETCH_REQUESTED = 'REPOS_FETCH_REQUESTED';
export const REPOS_FETCH_SUCCEEDED = 'REPOS_FETCH_SUCCEEDED';
export const SET_REPOS = 'SET_REPOS';
export const SET_QUERY = 'SET_QUERY';
